version: "3"
services:
  mirai:
    image: reprover/mirai-http:latest
    volumes:
      - ./mirai/config:/app/config
      - ./mirai/data:/app/data
      - ./mirai/logs:/app/logs
      - ./mirai/bots:/app/bots
      - ./mirai/plugins:/app/plugins
  service:
    image: node
    volumes:
      - .:/usr/local/app
      - ./wait-for-it.sh:/usr/local/app/wait-for-it.sh
    working_dir: /usr/local/app
    command: >
      /bin/bash -c '
      chmod 777 /usr/local/app/wait-for-it.sh;
      /usr/local/app/wait-for-it.sh mirai:8080 -t 60 -- npm run start:prod;
      '
  redis:
    image: redis
